### PR TITLE
Update the ReadTheDocs Site to Use the `furo` Theme

### LINKED ISSUE #94: Update ReadTheDocs Site to Use `furo` Theme
Currently the [deployed documentation](https://core-ct.readthedocs.io/en/latest/) for `core-ct` uses the `sphinx-wagtail-theme` (https://github.com/wagtail/sphinx-wagtail-theme). While this theme is functional, it is a bit hard to read and it doesn't support many customization options. As such, we should update the ReadTheDocs site to use the `furo`  theme (https://pradyunsg.me/furo/quickstart/) which addresses both of these issues.

The changes made in the issue were originally being addressed in #88 but it made more sense to split of the stylistic changes from the content changes since PR #92 (updating the `trim` function) and issue #93 (adding `numpy` indexing) might introduce breaking changes to the site.

### PR DESCRIPTION
**Pull request by Atomator**
Description copied from issue #94
> Currently the [deployed documentation](https://core-ct.readthedocs.io/en/latest/) for `core-ct` uses the `sphinx-wagtail-theme` (https://github.com/wagtail/sphinx-wagtail-theme). While this theme is functional, it is a bit hard to read and it doesn't support many customization options. As such, we should update the ReadTheDocs site to use the `furo`  theme (https://pradyunsg.me/furo/quickstart/) which addresses both of these issues.
> 
> The changes made in the issue were originally being addressed in #88 but it made more sense to split of the stylistic changes from the content changes since PR #92 (updating the `trim` function) and issue #93 (adding `numpy` indexing) might introduce breaking changes to the site.

Screenshots of the new documentation site are shown below:
Screenshot 2024-04-11 at 8 31 52 AM
Screenshot 2024-04-11 at 8 32 01 AM
Screenshot 2024-04-11 at 8 32 16 AM

### CODE REVIEW

**Comment by TheSecondReal0** [comment]
Could we change these link copy buttons back to the link icon instead of hashtags?
image
image

**Comment by TheSecondReal0** [comment]
My browser makes the website just barely too small width-wise to show the sidebar table of contents.
image
Ideally I would want it to look like this:
image

I'm not sure how easy it is but if we could tweak the dynamic sizing breakpoints to prioritize showing the sidebar at skinnier sizes it would be hype. My exact width in Vivaldi is 1827 pixels, on Firefox it's 1893 (1920x1080 screen). I think it would be optimal if the table of contents would display on 1080p displays.

**Comment by Atomator** [comment]
@TheSecondReal0
image

So I was able to replace the hashtag on the API documentation with a link icon (as seen above), but doing so ended up being pretty complicated and I'm thinking that we probably shouldn't keep that change. To get it to render as a link, I had to import the https://tabler.io/icons library as a webfont, import it in the CSS (meaning that we are loading in an entire font library just to render a single icon every time the page loads), render the link icon using an `::after` tag while also hiding the original `#`, and then finally use negative margins to move the new icon to left since the `#` still takes up space on the page even though it is invisible. The code for all that is below:

```css
@import "https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@3.2.0/dist/tabler-icons.min.css";

dl dt:hover>.headerlink {
    visibility: hidden;
} 

dl dt:hover>.headerlink::after {
    visibility: visible;
    font-family: "tabler-icons";
    content: "\eade";
    font-size: 13px;
    margin-left: -8px;
} 
```

In general, the main problem with making any stylistic changes to the site is that I don't have access to the raw HTML, so any changes have to made with CSS only, making it kinda difficult to change the site in any complex ways.

**Comment by Atomator** [comment]
Also, @TheSecondReal0 I tried to replicate the browser width issue that you encountered, but I wasn't able to. When I set the width of the page to `1827` it still rendered fine.

image

I looked into it a bit though and it turns out the breakpoint is set relative to the font size. The current breakpoint at which the sidebar disappears is `82em` (82 times the font size). This seems to be why I couldn't replicate your issue. We can definitely just increase the number or switch it over to pixels, but it probably wouldn't hurt to look into the issue on your device just to confirm that this is the problem.

If you run the below command in the browser console you can use it to get to the width of page in `em` units.
```javascript
window.innerWidth / parseFloat(
  getComputedStyle(
    document.querySelector('body')
  )['font-size']
)
```

**Comment by TheSecondReal0** [comment]
When I set the width to 1827 in the device tester it renders fine as well, but not when it's actually viewed like that. I wasn't able to measure the exact `em` amount in the normal screen but I estimate it to be between `77.5` and `78.25` (estimated by solving for `em`s per pixel at two widths then multiplying by `1827`)

**Comment by Atomator** [comment]
@TheSecondReal0 I looked into the responsive sizing and it doesn't look like I can fix it. All the breakpoints are calculated using the `$content-width`, `$sidebar-width`, and `$full-width` variables, however since they are `scss` variables, I have no way of updating them. The comment the author left on them says as much.

image

Not sure what you want to do about that

**Review by TheSecondReal0 — APPROVED** [review]

**Pull request merged**
