### PR TITLE
Created Initial README

### PR DESCRIPTION
**Pull request by Atomator**

### CODE REVIEW

**Review by KiraSqueak — APPROVED** [review]
Looks good

**Comment by TheSecondReal0** [comment]
Could put our names in the authors/credits section, maybe also Ryan and Zane

**Comment by Atomator** [comment]
> Could put our names in the authors/credits section, maybe also Ryan and Zane

Added our names to the README 👍🏾

**Review by TheSecondReal0 — APPROVED** [review]
Looks good!

**Review by carlameii — APPROVED** [review]
Looks good!

**Pull request merged**
