### PR TITLE
Add numpy like indexing to core and slice

### LINKED ISSUE #93: Add `numpy`-like indexing to Core and Slice
Add support for numpy style indexing to Core and Slice, to allow stuff like this:
```python
# trim a slice to only contain x indices 100-500
my_slice = my_slice[100:500]
# trim 100 off start of x-axis
my_slice = my_slice[100:]
# equivalent to my_slice[0:500]
my_slice = my_slice[:500]
# trim 100 off the end of the x axis
my_slice = my_slice[:-100]
# trim 100 off x-axis symmetrically
my_slice = my_slice[100:-100]
# trim a core to only contain y indices 200-300
my_core = my_core[:, 200:300]
# take a chunk of a core containing x indices 100-500, y indices 200-300, and z indices 300-1000
# equivalent to my_core.chunk(x1=100, x2=500, y1=200, y2=300, z1=300, z2=1000)
my_core = my_core[100:500, 200:300, 300:1000]
# take a slice at z=5
new_slice = my_core[:, :, 5]
# take a slice at z=5, containing x indices 100-500 and y indices 200-300
new_slice = my_core[100:500, 200:300, 5]
```

This would supersede `Core.chunk()`, `Core.slice()`, `Core.trim()`, and `Slice.trim()`. I think `Core.chunk()` should be removed in favor of indexing (or rewritten to be more intuitive, it's cumbersome right now). `Core.slice()` should be kept as an explicit way to create a `Slice`. I'm not sure about the `trim()` functions.

We should NOT allow assigning values via indexing, I think it's asking for inconsistency and weirdness. If the user wants to do something like that, they should access the `data` property of the `Core`/`Slice`

We must make sure `pixel_dimensions` are handled correctly when taking a slice with this method. 

There are a few edge cases to handle, for example:
```python
# if done on a numpy array, this would give a 1D vector containing all y values at x=1 and z=3
# there is no data type to represent a 1D vector in our library, so it is unclear what to return
# Ideas: return numpy data or raise IndexError
my_core[1, :, 3]

# this would give us a value at a single point if done on a numpy array
# Ideas: return numpy data or raise IndexError
my_core[1, 2, 3]
```

If we do this, we should document that you need to access the `Core`/`Slice`'s `data` property to actually access brightness values. I can see some confusion arising out of this syntax returning `Core`/`Slice` objects instead of arrays. We should discuss this with Ryan before finalizing any behavior.

We should also think about if this behavior is intuitive, especially compared to returning the numpy data itself instead of a new `Core` or `Slice` object.

### PR DESCRIPTION
**Pull request by TheSecondReal0**

### CODE REVIEW

**Comment by TheSecondReal0** [comment]
Found a weird edge case, you can technically specify a 1 pixel wide dimension like this with the `150:151`:
image
This returns a valid Slice and should work perfectly fine. It's just weird that this is allowed but you couldn't do the same thing by specifying only `150` instead of `150:151`. I'm not sure how to deal with this. 

If we make sure the difference is more than 1 then we're setting an arbitrary minimum size of 2, which feels really weird. I'm leaning most towards keeping this behavior, but this creates an inconsistency with not being allowed to use an int that would do the same thing.

The reason this technically works is that `my_core[150:151, 150:300, 11 // 2]` creates a data array with shape `(1, 150)` where `my_core[150:151, 150:300, 11 // 2]` creates a data array with shape `(150,)`

**Comment by TheSecondReal0** [comment]
I made it so the end index must come after the start index on all axes. This prevents reversing an axis via indexing. I want some feedback on what people think about this.

The rationale was that the data should stay mostly the same when indexing, and reversing might be confusing. Thinking about it now it's probably more confusing if it doesn't let you, but there are good error messages for it.

**Comment by TheSecondReal0** [comment]
I made it so a step isn't allowed when indexing, so no taking every other value or something. I think this makes sense, but would like to double check if anyone can think of valid use cases.

**Comment by TheSecondReal0** [comment]
> Found a weird edge case, you can technically specify a 1 pixel wide dimension like this with the `150:151`

Allow this behavior, have some priority to assign which axes a slice is taken/which dimension is removed.

**Comment by TheSecondReal0** [comment]
> > Found a weird edge case, you can technically specify a 1 pixel wide dimension like this with the `150:151`
> 
> Allow this behavior, have some priority to assign which axes a slice is taken/which dimension is removed.

Tried adding handling for this by converting excess integer indices into 1-width slices. This turned out to be more complex and hard to document. After discussion with the team we've decided not to handle these cases.

**Review by Atomator — APPROVED** [review]

**Pull request merged**
